# Generated by Django 5.1 on 2024-08-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRDLapp', '0002_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
    ]
