# Generated by Django 5.1 on 2024-08-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRDLapp', '0003_remove_post_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlengaiForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, null=True)),
                ('mname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('Identification', models.IntegerField()),
                ('mobile_tel', models.IntegerField()),
                ('office_tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('postal_address', models.CharField(max_length=255)),
                ('lawyers', models.CharField(max_length=255)),
                ('referred_by', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SopaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, null=True)),
                ('mname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('Identification', models.IntegerField()),
                ('mobile_tel', models.IntegerField()),
                ('office_tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('postal_address', models.CharField(max_length=255)),
                ('lawyers', models.CharField(max_length=255)),
                ('referred_by', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
